### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by iONinja** [shinnn/is-var-name#2]
Hi there.

Looking through your code, I noticed that a variable name's validity is verified by evaluating it (through a `Function` constructor). If an application was checking strings sent from clients, wouldn't those clients be able to inject arbitrary JavaScript which has access to the global scope, and be able to inflict great harm on the application?

**Comment by shinnn** [comment]
Can you provide an example code that can inflict great harm?

**Comment by iONinja** [comment]
@shinnn 

I just realised that passing an expression would prevent execution as you're passing the string as an argument, as well as the function body. My bad 😛.

**Comment by shinnn** [comment]
☺️
